load("@rules_zig//zig:defs.bzl", "zig_test")

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "goldens",
    srcs = glob([
        "goldens/**",
        "goldens/**/.keep",
    ]),
)

zig_test(
    name = "goldens_test",
    size = "small",
    data = [":goldens"],
    main = "goldens_test.zig",
    deps = [
        "//src:lib",
        "@rules_zig//zig/runfiles",
    ],
)
