//! Applet goldens loaded at runtime from `data/goldens/`.
//!
//! Loader: `data = [":goldens"]` + `@rules_zig//zig/runfiles`.
//! Proven rpath in this repo's Bazel test runfiles (bzlmod):
//! `_main/data/goldens/echo_hello/argv.txt`.
//! `Runfiles.create` → `withSourceRepo(bazel_builtin.current_repository)` →
//! `rlocationAlloc` that rpath → `openDir` parent `goldens/` → `readdir`.
//!
//! Each case directory contains `argv.txt` and `expected.txt`. Optional:
//! `stdin.txt`, `expected_status.txt`, `epipe.txt`, and a `files/` tree
//! planted onto the mem FS (`files/tmp/h` → `/tmp/h`). Skip `.keep`.
//! New cases add directories only; they do not edit this file.
//!
//! Oracle: uutils 0.9.0 (`UUTILS_PIN.md`). Capture stdout/status from that pin
//! on a developer machine, or from a documented deviation in the applet's
//! leading comment. Do not fetch during the build.

const std = @import("std");
const runfiles = @import("runfiles");
const utilz = @import("utilz");
const sys = utilz.sys;
const mem = utilz.mem;
const registry = utilz.registry;
const Ctx = utilz.Ctx;

const marker_rpath = "_main/data/goldens/echo_hello/argv.txt";
const argv_cap = 32;

fn parentPath(p: []const u8) ?[]const u8 {
    const i = std.mem.lastIndexOfScalar(u8, p, '/') orelse return null;
    if (i == 0) return "/";
    return p[0..i];
}

fn readAbs(allocator: std.mem.Allocator, path: []const u8) ![]u8 {
    const io = std.testing.io;
    const file = try std.Io.Dir.openFileAbsolute(io, path, .{});
    defer file.close(io);
    var buf: [4096]u8 = undefined;
    var r = file.reader(io, &buf);
    return r.interface.allocRemaining(allocator, .limited(64 * 1024));
}

fn readOptional(allocator: std.mem.Allocator, dir: []const u8, name: []const u8) !?[]u8 {
    const path = try std.fmt.allocPrint(allocator, "{s}/{s}", .{ dir, name });
    defer allocator.free(path);
    return readAbs(allocator, path) catch |err| switch (err) {
        error.FileNotFound => null,
        else => err,
    };
}

fn parseArgv(raw: []const u8, store: *[argv_cap][]const u8) ![]const []const u8 {
    const line = std.mem.trim(u8, raw, " \t\r\n");
    var n: usize = 0;
    var it = std.mem.splitScalar(u8, line, ' ');
    while (it.next()) |tok| {
        if (tok.len == 0) continue;
        if (n >= store.len) return error.TestUnexpectedResult;
        store[n] = tok;
        n += 1;
    }
    if (n == 0) return error.TestUnexpectedResult;
    return store[0..n];
}

fn parseStatus(raw: []const u8) !u8 {
    const line = std.mem.trim(u8, raw, " \t\r\n");
    return std.fmt.parseInt(u8, line, 10) catch return error.TestUnexpectedResult;
}

fn nestedHook(world: *mem.Mem, argv: []const []const u8, stdin: sys.Fd, stdout: sys.Fd, stderr: sys.Fd) sys.Error!u8 {
    if (argv.len == 0) return error.EINVAL;
    const base = argv[0];
    const name = if (std.mem.lastIndexOfScalar(u8, base, '/')) |i| base[i + 1 ..] else base;
    const applet = registry.find(name) orelse return error.ENOENT;
    var arena_state = std.heap.ArenaAllocator.init(world.allocator);
    defer arena_state.deinit();
    const arena = arena_state.allocator();
    var zargs: [argv_cap][:0]const u8 = undefined;
    if (argv.len > zargs.len) return error.EINVAL;
    for (argv, 0..) |a, i| zargs[i] = arena.dupeZ(u8, a) catch return error.ENOMEM;
    var ctx = Ctx{
        .args = zargs[0..argv.len],
        .gpa = arena,
        .stdin = stdin,
        .stdout = stdout,
        .stderr = stderr,
    };
    return applet.run(&ctx);
}

fn mkdirParents(path: []const u8) !void {
    var i: usize = 1;
    while (i < path.len) : (i += 1) {
        if (path[i] != '/') continue;
        sys.mkdir(path[0..i]) catch |err| switch (err) {
            error.EEXIST => {},
            else => return err,
        };
    }
}

fn writeFixture(path: []const u8, bytes: []const u8) !void {
    try mkdirParents(path);
    const fd = try sys.open(path, .{ .write = true, .create = true, .trunc = true });
    try sys.writeAll(fd, bytes);
    sys.close(fd);
}

fn plantWalk(allocator: std.mem.Allocator, files_root: []const u8, rel: []const u8) !void {
    const io = std.testing.io;
    const abs = if (rel.len == 0)
        files_root
    else
        try std.fmt.allocPrint(allocator, "{s}/{s}", .{ files_root, rel });
    defer if (rel.len != 0) allocator.free(abs);

    var dir = std.Io.Dir.openDirAbsolute(io, abs, .{ .iterate = true }) catch |err| switch (err) {
        error.FileNotFound => {
            if (rel.len == 0) return;
            return err;
        },
        else => return err,
    };
    defer dir.close(io);

    var it = dir.iterate();
    while (try it.next(io)) |entry| {
        const child_rel = if (rel.len == 0)
            try allocator.dupe(u8, entry.name)
        else
            try std.fmt.allocPrint(allocator, "{s}/{s}", .{ rel, entry.name });
        defer allocator.free(child_rel);
        const dest = try std.fmt.allocPrint(allocator, "/{s}", .{child_rel});
        defer allocator.free(dest);

        if (entry.kind == .directory) {
            sys.mkdir(dest) catch |err| switch (err) {
                error.EEXIST => {},
                else => return err,
            };
            try plantWalk(allocator, files_root, child_rel);
            continue;
        }
        if (std.mem.eql(u8, entry.name, ".keep")) continue;
        const src = try std.fmt.allocPrint(allocator, "{s}/{s}", .{ files_root, child_rel });
        defer allocator.free(src);
        const bytes = try readAbs(allocator, src);
        defer allocator.free(bytes);
        try writeFixture(dest, bytes);
    }
}

fn plantFiles(allocator: std.mem.Allocator, case_dir: []const u8) !void {
    const files_root = try std.fmt.allocPrint(allocator, "{s}/files", .{case_dir});
    defer allocator.free(files_root);
    try plantWalk(allocator, files_root, "");
}

fn run(world: *mem.Mem, args: []const []const u8, stdout_fd: sys.Fd) !struct { status: u8, stdout: []u8 } {
    var arena_state = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena_state.deinit();
    const arena = arena_state.allocator();
    var zargs: [argv_cap][:0]const u8 = undefined;
    if (args.len > zargs.len) return error.TestUnexpectedResult;
    for (args, 0..) |a, i| zargs[i] = try arena.dupeZ(u8, a);
    const applet = registry.find(args[0]) orelse return error.TestUnexpectedResult;
    world.stdout_buf.clearRetainingCapacity();
    var ctx = Ctx{
        .args = zargs[0..args.len],
        .gpa = arena,
        .stdin = 0,
        .stdout = stdout_fd,
        .stderr = 2,
    };
    const status = applet.run(&ctx);
    return .{
        .status = status,
        .stdout = try std.testing.allocator.dupe(u8, world.stdout_buf.items),
    };
}

fn runCase(dir: []const u8, name: []const u8) !void {
    const allocator = std.testing.allocator;
    const argv_path = try std.fmt.allocPrint(allocator, "{s}/argv.txt", .{dir});
    defer allocator.free(argv_path);
    const argv_raw = try readAbs(allocator, argv_path);
    defer allocator.free(argv_raw);
    const expected_path = try std.fmt.allocPrint(allocator, "{s}/expected.txt", .{dir});
    defer allocator.free(expected_path);
    const expected = try readAbs(allocator, expected_path);
    defer allocator.free(expected);

    const world = try mem.Mem.init(allocator);
    defer world.deinit();
    world.spawn_hook = nestedHook;
    world.attach();
    defer sys.detach();

    try plantFiles(allocator, dir);
    if (try readOptional(allocator, dir, "stdin.txt")) |stdin| {
        defer allocator.free(stdin);
        try world.stdin_buf.appendSlice(world.allocator, stdin);
    }
    const want_status: u8 = if (try readOptional(allocator, dir, "expected_status.txt")) |raw| blk: {
        defer allocator.free(raw);
        break :blk try parseStatus(raw);
    } else 0;

    var stdout_fd: sys.Fd = 1;
    if (try readOptional(allocator, dir, "epipe.txt")) |flag| {
        defer allocator.free(flag);
        const pair = try sys.pipe();
        sys.close(pair.r);
        stdout_fd = pair.w;
    }

    var store: [argv_cap][]const u8 = undefined;
    const args = try parseArgv(argv_raw, &store);
    const got = try run(world, args, stdout_fd);
    defer allocator.free(got.stdout);
    if (got.status != want_status) {
        std.debug.print("golden {s} status want={d} got={d}\n", .{ name, want_status, got.status });
        return error.TestUnexpectedResult;
    }
    if (!std.mem.eql(u8, expected, got.stdout)) {
        std.debug.print("golden {s} stdout mismatch\n", .{name});
        std.debug.print("want ({d}): {s}\n", .{ expected.len, expected });
        std.debug.print("got  ({d}): {s}\n", .{ got.stdout.len, got.stdout });
        return error.TestUnexpectedResult;
    }
}

test "goldens" {
    const allocator = std.testing.allocator;
    const io = std.testing.io;
    const argv0 = try std.process.executablePathAlloc(io, allocator);
    defer allocator.free(argv0);
    var environ_map = try std.testing.environ.createMap(allocator);
    defer environ_map.deinit();

    var r_ = (try runfiles.Runfiles.create(.{
        .allocator = allocator,
        .io = io,
        .argv0 = argv0,
        .environ_map = &environ_map,
    })) orelse return error.RunfilesNotFound;
    defer r_.deinit(allocator);
    const r = r_.withSourceRepo(@import("bazel_builtin").current_repository);
    const marker = try r.rlocationAlloc(allocator, marker_rpath) orelse return error.RPathNotFound;
    defer allocator.free(marker);
    const case_dir = parentPath(marker) orelse return error.RPathNotFound;
    const goldens_dir = parentPath(case_dir) orelse return error.RPathNotFound;

    var dir = try std.Io.Dir.openDirAbsolute(io, goldens_dir, .{ .iterate = true });
    defer dir.close(io);

    var names: std.ArrayListUnmanaged([]u8) = .empty;
    defer {
        for (names.items) |n| allocator.free(n);
        names.deinit(allocator);
    }
    var it = dir.iterate();
    while (try it.next(io)) |entry| {
        if (entry.kind != .directory) continue;
        try names.append(allocator, try allocator.dupe(u8, entry.name));
    }
    std.mem.sort([]u8, names.items, {}, struct {
        fn less(_: void, a: []u8, b: []u8) bool {
            return std.mem.lessThan(u8, a, b);
        }
    }.less);
    if (names.items.len == 0) return error.TestUnexpectedResult;

    var failed: usize = 0;
    for (names.items) |name| {
        const case = try std.fmt.allocPrint(allocator, "{s}/{s}", .{ goldens_dir, name });
        defer allocator.free(case);
        runCase(case, name) catch {
            failed += 1;
        };
    }
    if (failed != 0) {
        std.debug.print("{d} golden(s) failed\n", .{failed});
        return error.TestUnexpectedResult;
    }
}
